version: '3.2'

services:

  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ".env"
    network_mode: 'host'

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    network_mode: 'host'

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    network_mode: 'host'

  tgbot:
    container_name: bot
    build:
      context: .
    command: python3 add.py
    restart: always

    env_file:
      - ".env"
